
version: '3'
services:
  postgres-local:
    image: postgres:latest
    container_name: my_postgres_local_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker_local
    ports:
      - "5053:5432"
    volumes:
      - postgres-local-data:/var/lib/postgresql/data

  postgres-testing:
    image: postgres:latest
    container_name: my_postgres_testing_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker_testing
    ports:
      - "5054:5432"
    volumes:
      - postgres-testing-data:/var/lib/postgresql/data

  postgres-production:
    image: postgres:latest
    container_name: my_postgres_production_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker_production
    ports:
      - "5055:5432"
    volumes:
      - postgres-production-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_application_container
    ports:
      - "8083:8080"
    depends_on:
      - postgres-${APP_ENV:-production}
    env_file:
      - .env.${APP_ENV:-production}
    volumes:
      - ./logs:/app/logs

volumes:
  postgres-local-data:
  postgres-testing-data:
  postgres-production-data:














