version: '3'
services:
  postgres-testing:
    image: postgres:latest
    container_name: my_postgres_testing_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker_testing
    ports:
      - "5054:5432"
    volumes:
      - postgres-testing-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_application_container
    ports:
      - "8084:8080"
    depends_on:
      - postgres-testing
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-testing:5432/docker_testing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  postgres-testing-data:

      
      
      
      
  